### PR TITLE
Switch to python

### PR DESCRIPTION
**Pull request by AGitsjustsilver**
### Message

This is the first example of how the project could work. Look over and let me know if there's anything to clarify

### Docs
* [Flask](https://flask.palletsprojects.com/en/2.0.x/)
* [Flask-SQLAlchemy](https://flask-sqlalhemy.palletsprojects.com/en/2.x/)
* [Flask-Restful](https://flask-restful.readthedocs.io/en/latest/quickstart.html)
* [Flask-Marshmallow](https://flask-marshmallow.readthedocs.io/en/latest/)
* [Python MYSQL Connector](https://dev.mysql.com/doc/connector-python/en/)

### CODE REVIEW

**Review by Maddy54652 — APPROVED** [review]
Holy Sh*t Allesandro that is an incredible amount of work. It looks very great though. I am more than okay with merging this. Great job!

**Review by TrClark3 — COMMENTED** [review]
Looks good! Still can't seem to get the docker-compose to build/run properly on my machine, even with the creation of the "users" db through adminer. But this is likely an isolated issue for my machine. I'm curious to see if it works for the other team members.

**Review by sheradyn — APPROVED** [review]
Looks great to me!

**Review by WestoneGoidboige — APPROVED** [review]
10/10

**Pull request merged**
